services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    env_file:
      - .env
    ports:
      - "${PGADMIN_DEFAULT_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  postgres_data:
  pgadmin_data:
